name: digifarmer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  hexcolor: ^3.0.1
  provider: ^6.0.5

  slide_popup_dialog_null_safety: ^1.0.0
  csc_picker: ^0.2.1
  awesome_snackbar_content: ^0.1.2
  path_provider: ^2.0.12
  intl: ^0.17.0
  flutter_datetime_picker: ^1.5.1
  pie_chart: ^5.3.2
  url_launcher: ^6.1.10
  animated_widgets: ^1.1.0
  custom_refresh_indicator: ^2.0.1
  confirm_dialog: ^1.0.1
  liquid_pull_to_refresh: ^3.0.1
  firebase_auth: ^4.1.1
  firebase_auth_oauth: ^1.2.2
  google_sign_in: ^5.4.3
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  flutter_animate: 1.0.0
  flutter_cache_manager: 3.3.0
  flutter_spinkit: 5.1.0
  font_awesome_flutter: 10.1.0
  multi_image_picker_view: ^0.0.8
  image_picker: ^0.8.3
  galleryimage: ^1.2.0
  json_serializable: ^6.5.4
  change_app_package_name: ^1.1.0
  password_text_field: ^1.1.0
  carousel_slider: ^4.2.1
  country_list_pick: ^1.0.1+6
  flutter_holo_date_picker: ^1.1.0
  flutter_rating_bar: ^4.0.1
  passwordfield: ^0.1.0
  enhanced_drop_down: ^0.1.7+1
  expandable_datatable: ^0.0.6
  connectivity_plus: ^2.3.0
  flutter_staggered_grid_view: ^0.6.2
  date_time_picker: "^2.1.0"
  textfields: ^0.0.3
  dropdown_button2: ^1.9.2
  expandable: ^5.0.1
  flutter_otp_text_field: ^1.1.0+2
  country_dial_code: ^1.2.0
  google_fonts: ^3.0.1
  get: ^4.6.5
  timer_count_down: ^2.2.1
  flutter_onboard: ^2.0.0
  loading_animation_widget: ^1.2.0+3
  flutter_onboarding_screen: ^2.0.2
  shared_preferences: ^2.0.15
  http: ^0.13.5
  upgrader: ^6.0.1
  animated_text_kit:
  firebase_core: ^2.6.1
  edge_alert: ^0.0.1
  modal_progress_hud: ^0.1.3
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_vector_icons: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
     - assets/logo/
     - assets/bg/
     - assets/user.png
     - assets/onboard/
     - assets/category/
     - assets/images/
     - assets/profile/
     - assets/farm/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages







